name: Build and Push Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: quay.io
  IMAGE_NAME: jdcasey/myshift

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run black
        run: black --check --line-length 120 .

      - name: Run isort
        run: isort --check-only --line-length 120 .

  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run bandit
        run: bandit -r myshift/

  build-and-push:
    needs: [lint, security]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: myshift
          containerfiles: |
            ./Containerfile
          tags: latest ${{ github.sha }}
          oci: true

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/jdcasey
          username: ${{ secrets.QUAY_BOT_USER }}
          password: ${{ secrets.QUAY_BOT_PASSWORD }}