name: PR Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy bandit safety

      - name: Run black
        run: black --check .

      - name: Run isort
        run: isort --check-only .

      - name: Run flake8
        run: flake8 .

      - name: Run mypy
        run: mypy myshift/

  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run bandit
        run: bandit -r myshift/ -f json -o bandit-results.json

      - name: Run safety
        run: safety check

      - name: Upload bandit results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: bandit-results.json
          category: "Bandit Security Scan"

  container:
    name: Container Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Buildah
        uses: redhat-actions/buildah-setup@v2
        with:
          buildah-version: latest

      - name: Build container
        uses: redhat-actions/buildah-build@v2
        with:
          image: myshift
          containerfiles: |
            ./Containerfile
          tags: pr-check
          oci: true

      - name: Run container security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myshift:pr-check'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH' 